import product1 from "@/assets/product-1.jpg";
import product2 from "@/assets/product-2.jpg";
import product3 from "@/assets/product-3.jpg";
import product4 from "@/assets/product-4.jpg";
import thriftCapBlack from "@/assets/thrift-cap-black.jpg";
import thriftCapTan from "@/assets/thrift-cap-tan.jpg";
import thriftCapGreen from "@/assets/thrift-cap-green.jpg";
import thriftTeeWhite from "@/assets/thrift-tee-white.jpg";
import thriftFlannelNavy from "@/assets/thrift-flannel-navy.jpg";
import thriftPoloStripe from "@/assets/thrift-polo-stripe.jpg";
import thriftBagBrown from "@/assets/thrift-bag-brown.jpg";
import thriftBagBlack from "@/assets/thrift-bag-black.jpg";
import thriftBagDenim from "@/assets/thrift-bag-denim.jpg";
import thriftBeanieCharcoal from "@/assets/thrift-beanie-charcoal.jpg";
import thriftBucketOlive from "@/assets/thrift-bucket-olive.jpg";
import thriftBalaclavaBlack from "@/assets/thrift-balaclava-black.jpg";

export interface Product {
  id: string;
  name: string;
  price: number;
  category: "men" | "women" | "unisex" | "thrift";
  thriftCategory?: "caps" | "shirts" | "bags" | "headgear";
  tag?: "new" | "bestseller";
  sourceTag?: "brand-new" | "thrifted";
  sizes: string[];
  image: string;
  imageAlt?: string;
  description: string;
}

export const products: Product[] = [
  // ═══════════════════════════════════════════
  // BRAND NEW — Men
  // ═══════════════════════════════════════════
  {
    id: "essential-hoodie-sand",
    name: "Essential Hoodie — Sand",
    price: 4800,
    category: "unisex",
    tag: "bestseller",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: product1,
    description: "Heavyweight 400gsm French terry. Oversized fit, ribbed cuffs, kangaroo pocket. Made for all-day comfort.",
  },
  {
    id: "relaxed-jogger-midnight",
    name: "Relaxed Jogger — Midnight",
    price: 3900,
    category: "men",
    tag: "bestseller",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL"],
    image: product2,
    description: "Tapered fit jogger in premium brushed fleece. Elastic waistband with internal drawcord.",
  },
  {
    id: "oversized-tee-cream",
    name: "Oversized Tee — Cream",
    price: 2400,
    category: "unisex",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: product3,
    description: "250gsm cotton jersey with dropped shoulders. Boxy silhouette for effortless layering.",
  },
  {
    id: "utility-jacket-olive",
    name: "Utility Jacket — Olive",
    price: 7200,
    category: "men",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["M", "L", "XL"],
    image: product4,
    description: "Water-resistant ripstop shell with fleece liner. Full zip with branded hardware.",
  },
  {
    id: "cargo-pants-khaki",
    name: "Cargo Pants — Khaki",
    price: 4500,
    category: "men",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL"],
    image: product2,
    description: "Relaxed straight-leg cargo in washed cotton twill. Six-pocket design with adjustable ankle.",
  },
  {
    id: "heavyweight-crewneck-charcoal",
    name: "Heavyweight Crewneck — Charcoal",
    price: 4200,
    category: "men",
    tag: "bestseller",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: product1,
    description: "Premium 380gsm loopback terry crewneck. Ribbed trims, relaxed fit, subtle embroidered logo.",
  },
  {
    id: "coaches-jacket-black",
    name: "Coaches Jacket — Black",
    price: 5800,
    category: "men",
    sourceTag: "brand-new",
    sizes: ["M", "L", "XL"],
    image: product4,
    description: "Classic coaches jacket in nylon shell with satin lining. Snap front closure, minimalist branding.",
  },
  {
    id: "track-pants-navy",
    name: "Track Pants — Navy",
    price: 3600,
    category: "men",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL"],
    image: product2,
    description: "Side-stripe track pant in interlock jersey. Zip pockets, elastic hem. Vintage sportswear inspired.",
  },
  {
    id: "essential-shorts-stone",
    name: "Essential Shorts — Stone",
    price: 2800,
    category: "men",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL"],
    image: product3,
    description: "Relaxed mesh-lined shorts in stone wash. Drawcord waist, side pockets, above-knee length.",
  },

  // ═══════════════════════════════════════════
  // BRAND NEW — Women
  // ═══════════════════════════════════════════
  {
    id: "wide-leg-pant-stone",
    name: "Wide Leg Pant — Stone",
    price: 4200,
    category: "women",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product1,
    description: "Relaxed wide-leg trouser in washed cotton twill. High waist with pleated front.",
  },
  {
    id: "cropped-hoodie-espresso",
    name: "Cropped Hoodie — Espresso",
    price: 4500,
    category: "women",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product2,
    description: "Cropped silhouette with raw-edge hem. Heavyweight fleece with tonal embroidery.",
  },
  {
    id: "ribbed-tank-oat",
    name: "Ribbed Tank — Oat",
    price: 1800,
    category: "women",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product3,
    description: "Form-fitting ribbed cotton tank in warm oat. Scoop neck, elongated length for layering.",
  },
  {
    id: "oversized-blazer-sand",
    name: "Oversized Blazer — Sand",
    price: 6800,
    category: "women",
    tag: "bestseller",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product4,
    description: "Unlined linen-blend oversized blazer. Single button closure, padded shoulders, relaxed drape.",
  },
  {
    id: "flare-jogger-mocha",
    name: "Flare Jogger — Mocha",
    price: 3800,
    category: "women",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product1,
    description: "High-waist flared jogger in brushed fleece. Elastic waistband with flared leg opening.",
  },
  {
    id: "bodysuit-black",
    name: "Bodysuit — Black",
    price: 2200,
    category: "women",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product2,
    description: "Seamless stretch bodysuit in matte black. Square neck, snap closure, second-skin fit.",
  },
  {
    id: "mini-skirt-charcoal",
    name: "Mini Skirt — Charcoal",
    price: 2600,
    category: "women",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product3,
    description: "Pleated mini skirt in heavyweight cotton twill. Side zip, structured A-line silhouette.",
  },
  {
    id: "puffer-vest-cream",
    name: "Puffer Vest — Cream",
    price: 5200,
    category: "women",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["XS", "S", "M", "L"],
    image: product4,
    description: "Cropped puffer vest with recycled fill. Stand collar, two-way zip, packable design.",
  },

  // ═══════════════════════════════════════════
  // BRAND NEW — Unisex
  // ═══════════════════════════════════════════
  {
    id: "zip-hoodie-slate",
    name: "Zip Hoodie — Slate",
    price: 5200,
    category: "unisex",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: product4,
    description: "Full-zip hoodie in washed slate. Split kangaroo pockets, brushed interior, YKK hardware.",
  },
  {
    id: "graphic-tee-vintage-black",
    name: "Graphic Tee — Vintage Black",
    price: 2600,
    category: "unisex",
    tag: "bestseller",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: product3,
    description: "Acid-washed graphic tee with distressed print. Heavyweight cotton, oversized boxy fit.",
  },
  {
    id: "essential-hoodie-midnight",
    name: "Essential Hoodie — Midnight",
    price: 4800,
    category: "unisex",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: product1,
    description: "Same beloved essential hoodie in deep midnight. 400gsm French terry, tonal branding.",
  },
  {
    id: "sweatpants-heather-grey",
    name: "Sweatpants — Heather Grey",
    price: 3800,
    category: "unisex",
    tag: "new",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL"],
    image: product2,
    description: "Classic straight-leg sweatpant in heather grey. Elastic waist with drawcord, side pockets.",
  },
  {
    id: "longline-tee-olive",
    name: "Longline Tee — Olive",
    price: 2200,
    category: "unisex",
    sourceTag: "brand-new",
    sizes: ["S", "M", "L", "XL"],
    image: product3,
    description: "Extended-length tee with curved hem. Soft-washed cotton, relaxed through the body.",
  },

  // ═══════════════════════════════════════════
  // THRIFT — Caps
  // ═══════════════════════════════════════════
  {
    id: "thrift-vintage-cap-black",
    name: "Vintage Cap — Black",
    price: 1200,
    category: "thrift",
    thriftCategory: "caps",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapBlack,
    description: "Authentic vintage baseball cap in washed black. Adjustable strap back. Pre-loved in excellent condition.",
  },
  {
    id: "thrift-retro-cap-tan",
    name: "Retro Cap — Tan",
    price: 1000,
    category: "thrift",
    thriftCategory: "caps",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapTan,
    description: "Classic six-panel cap in warm tan. Embroidered logo detail. Authentic vintage piece.",
  },
  {
    id: "thrift-corduroy-cap-green",
    name: "Corduroy Cap — Green",
    price: 1100,
    category: "thrift",
    thriftCategory: "caps",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapGreen,
    description: "Premium corduroy newsboy cap in forest green. Vintage silhouette with modern appeal.",
  },
  {
    id: "thrift-trucker-cap-red",
    name: "Trucker Cap — Red",
    price: 900,
    category: "thrift",
    thriftCategory: "caps",
    tag: "bestseller",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapBlack,
    description: "Classic mesh-back trucker cap in faded red. Snapback closure. Authentic 90s vintage find.",
  },
  {
    id: "thrift-fitted-cap-navy",
    name: "Fitted Cap — Navy",
    price: 1400,
    category: "thrift",
    thriftCategory: "caps",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapTan,
    description: "New Era style fitted cap in deep navy. Flat brim, structured crown. Pristine condition.",
  },
  {
    id: "thrift-dad-cap-cream",
    name: "Dad Cap — Cream",
    price: 800,
    category: "thrift",
    thriftCategory: "caps",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapGreen,
    description: "Soft unstructured dad cap in vintage cream. Brass buckle closure. Worn-in patina.",
  },
  {
    id: "thrift-snapback-camo",
    name: "Snapback — Camo",
    price: 1100,
    category: "thrift",
    thriftCategory: "caps",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapBlack,
    description: "Woodland camo snapback with flat brim. Bold streetwear statement. Vintage military surplus vibe.",
  },
  {
    id: "thrift-5panel-grey",
    name: "5-Panel — Grey",
    price: 950,
    category: "thrift",
    thriftCategory: "caps",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftCapTan,
    description: "Minimalist five-panel cap in heather grey. Nylon strap closure. Skate-inspired silhouette.",
  },

  // ═══════════════════════════════════════════
  // THRIFT — Shirts & Tees
  // ═══════════════════════════════════════════
  {
    id: "thrift-graphic-tee-white",
    name: "Graphic Tee — White",
    price: 1500,
    category: "thrift",
    thriftCategory: "shirts",
    tag: "bestseller",
    sourceTag: "thrifted",
    sizes: ["M", "L", "XL"],
    image: thriftTeeWhite,
    description: "Authentic vintage graphic t-shirt. Bold print on heavyweight cotton. One-of-a-kind find.",
  },
  {
    id: "thrift-flannel-shirt-navy",
    name: "Flannel Shirt — Navy",
    price: 2200,
    category: "thrift",
    thriftCategory: "shirts",
    sourceTag: "thrifted",
    sizes: ["M", "L"],
    image: thriftFlannelNavy,
    description: "Heavyweight brushed flannel in navy plaid. Authentic vintage workwear. Button-down collar.",
  },
  {
    id: "thrift-polo-stripe",
    name: "Striped Polo — Navy/Cream",
    price: 1800,
    category: "thrift",
    thriftCategory: "shirts",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["M", "L", "XL"],
    image: thriftPoloStripe,
    description: "Classic striped polo in navy and cream. Soft cotton piqué. Vintage preppy aesthetic.",
  },
  {
    id: "thrift-band-tee-black",
    name: "Band Tee — Black",
    price: 1800,
    category: "thrift",
    thriftCategory: "shirts",
    tag: "bestseller",
    sourceTag: "thrifted",
    sizes: ["L", "XL"],
    image: thriftTeeWhite,
    description: "Rare vintage band tour tee in faded black. Single-stitch construction. Collector's piece.",
  },
  {
    id: "thrift-denim-shirt-light",
    name: "Denim Shirt — Light Wash",
    price: 2500,
    category: "thrift",
    thriftCategory: "shirts",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["M", "L"],
    image: thriftFlannelNavy,
    description: "Classic western denim shirt in light stone wash. Pearl snap buttons. Authentic vintage Americana.",
  },
  {
    id: "thrift-hawaiian-shirt",
    name: "Hawaiian Shirt — Floral",
    price: 2000,
    category: "thrift",
    thriftCategory: "shirts",
    sourceTag: "thrifted",
    sizes: ["L", "XL"],
    image: thriftPoloStripe,
    description: "Bold floral print Hawaiian shirt. Rayon fabric, camp collar. Perfect summer statement piece.",
  },
  {
    id: "thrift-rugby-stripe",
    name: "Rugby Shirt — Stripe",
    price: 2400,
    category: "thrift",
    thriftCategory: "shirts",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["M", "L", "XL"],
    image: thriftTeeWhite,
    description: "Heavy cotton rugby shirt with bold horizontal stripes. Rubber buttons, reinforced collar.",
  },
  {
    id: "thrift-henley-oatmeal",
    name: "Henley Tee — Oatmeal",
    price: 1400,
    category: "thrift",
    thriftCategory: "shirts",
    sourceTag: "thrifted",
    sizes: ["M", "L"],
    image: thriftFlannelNavy,
    description: "Waffle-knit henley in oatmeal. Three-button placket. Soft worn-in feel, vintage workwear staple.",
  },

  // ═══════════════════════════════════════════
  // THRIFT — Bags
  // ═══════════════════════════════════════════
  {
    id: "thrift-leather-bag-brown",
    name: "Leather Satchel — Brown",
    price: 3800,
    category: "thrift",
    thriftCategory: "bags",
    tag: "bestseller",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBagBrown,
    description: "Authentic designer leather satchel in rich brown. Gold-tone hardware. Verified authentic.",
  },
  {
    id: "thrift-crossbody-black",
    name: "Crossbody Bag — Black",
    price: 2800,
    category: "thrift",
    thriftCategory: "bags",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBagBlack,
    description: "Designer crossbody in smooth black leather. Compact silhouette with adjustable strap. Authenticated.",
  },
  {
    id: "thrift-denim-tote",
    name: "Denim Tote Bag",
    price: 1600,
    category: "thrift",
    thriftCategory: "bags",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBagDenim,
    description: "Vintage denim tote with generous capacity. Sturdy construction, casual everyday carry.",
  },
  {
    id: "thrift-messenger-olive",
    name: "Messenger Bag — Olive",
    price: 3200,
    category: "thrift",
    thriftCategory: "bags",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBagBrown,
    description: "Military-style canvas messenger in olive drab. Brass buckles, multiple compartments. Vintage surplus.",
  },
  {
    id: "thrift-duffle-tan",
    name: "Duffle Bag — Tan",
    price: 4200,
    category: "thrift",
    thriftCategory: "bags",
    tag: "bestseller",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBagDenim,
    description: "Large canvas and leather duffle in tan. Zip-top opening, removable shoulder strap. Weekend-ready.",
  },
  {
    id: "thrift-mini-backpack-black",
    name: "Mini Backpack — Black",
    price: 2600,
    category: "thrift",
    thriftCategory: "bags",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBagBlack,
    description: "Compact faux-leather mini backpack. Zip closure, front pocket, adjustable straps. Daily essentials.",
  },
  {
    id: "thrift-fanny-pack-neon",
    name: "Fanny Pack — Neon",
    price: 1200,
    category: "thrift",
    thriftCategory: "bags",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBagDenim,
    description: "Retro 90s fanny pack in neon colorblock. Zip compartment, adjustable belt. Festival-ready throwback.",
  },

  // ═══════════════════════════════════════════
  // THRIFT — Headgear
  // ═══════════════════════════════════════════
  {
    id: "thrift-beanie-charcoal",
    name: "Beanie — Charcoal",
    price: 800,
    category: "thrift",
    thriftCategory: "headgear",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBeanieCharcoal,
    description: "Ribbed knit beanie in charcoal grey. Soft acrylic blend. Authentic vintage streetwear.",
  },
  {
    id: "thrift-bucket-hat-olive",
    name: "Bucket Hat — Olive",
    price: 1100,
    category: "thrift",
    thriftCategory: "headgear",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBucketOlive,
    description: "Canvas bucket hat in olive drab. Vintage military surplus style. Wide brim for all-weather wear.",
  },
  {
    id: "thrift-balaclava-black",
    name: "Balaclava — Black",
    price: 1400,
    category: "thrift",
    thriftCategory: "headgear",
    tag: "bestseller",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBalaclavaBlack,
    description: "Sleek black balaclava in stretch knit. Urban streetwear essential. Full face coverage with eye slit.",
  },
  {
    id: "thrift-beanie-burgundy",
    name: "Beanie — Burgundy",
    price: 900,
    category: "thrift",
    thriftCategory: "headgear",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBeanieCharcoal,
    description: "Chunky knit beanie in deep burgundy. Fold-over cuff, cozy wool blend. Winter essential.",
  },
  {
    id: "thrift-bucket-hat-black",
    name: "Bucket Hat — Black",
    price: 1000,
    category: "thrift",
    thriftCategory: "headgear",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBucketOlive,
    description: "Nylon bucket hat in solid black. Packable, reversible design. 90s streetwear archive piece.",
  },
  {
    id: "thrift-visor-white",
    name: "Visor — White",
    price: 700,
    category: "thrift",
    thriftCategory: "headgear",
    tag: "new",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBalaclavaBlack,
    description: "Classic sport visor in crisp white. Adjustable velcro strap. Vintage tennis club aesthetic.",
  },
  {
    id: "thrift-trapper-hat-brown",
    name: "Trapper Hat — Brown",
    price: 1600,
    category: "thrift",
    thriftCategory: "headgear",
    tag: "bestseller",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBeanieCharcoal,
    description: "Faux-fur lined trapper hat in brown suede. Ear flaps with snap closure. Cold-weather statement.",
  },
  {
    id: "thrift-headband-knit",
    name: "Knit Headband — Cream",
    price: 600,
    category: "thrift",
    thriftCategory: "headgear",
    sourceTag: "thrifted",
    sizes: ["One Size"],
    image: thriftBucketOlive,
    description: "Wide cable-knit headband in natural cream. Soft merino wool blend. Boho vintage vibes.",
  },
];

export function formatPrice(price: number): string {
  return `KSh ${price.toLocaleString()}`;
}
